name: Build and Test 

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    name: Run test suite
    runs-on: ubuntu-latest
    container:
      image: blazedenigma/cpp_server:1.0
      ports:
        - 8080
      volumes:
        - .:/workspace
    
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Build cmake project
      run: |
        git config --global --add safe.directory /workspace
        cd /workspace
        git submodule init
        git submodule update
        sh ./configure.sh
        sh ./build.sh

    - name: Run cpp_server
      run: |
        sh ./run_server.sh & sleep 5 && sh ./test_run.sh