name: Build and Test 

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    name: Run test suite
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup docker buildx
      uses: docker/setup-buildx-action@v2

    - name: Build docker image
      uses: docker/build-push-action@v4
      with:
        context: .
        file: ./.devcontainer/Dockerfile
        push: false
        tags: cpp_server:latest

    - name: Build cmake project
      run: |
        docker run -it cpp_server:latest &&
        sh ./configure.sh &&
        sh ./build.sh

    - name: Run cpp_server
      run: |
        sh ./run_server.sh &
        sleep 5 &&
        sh ./test_run.sh