name: Build and Test 

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    name: Run test suite
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup docker buildx
      uses: docker/setup-buildx-action@v2

    - name: Build docker image
      uses: docker/build-push-action@v4
      with:
        context: .
        file: ./.devcontainer/Dockerfile
        push: false
        tags: cpp_server:latest

    - name: Build cmake project
      run: |
        docker run --name cpp_server -d cpp_server:latest tail -f /dev/null &&
        docker exec cpp_server git submodule init &&
        docker exec cpp_server sh ./configure.sh &&
        docker exec cpp_server sh ./build.sh

    - name: Run cpp_server
      run: |
        docker exec cpp_server sh ./run_server.sh &
        docker exec cpp_server sleep 5 &&
        docker exec cpp_server sh ./test_run.sh