name: Build and Test 

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    name: Run test suite
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Build docker image
      run: |
        echo ---Building docker image---
        docker build . --file ./.devcontainer/Dockerfile --tag cpp_server:latest
        echo ---Finished building docker image---
