name: Build and Test 

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    name: Run test suite
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup docker buildx
      uses: docker/setup-buildx-action@v2

    - name: Build docker image
      uses: docker/build-push-action@v4
      with:
        context: .
        file: ./.devcontainer/Dockerfile
        push: false
        tags: cpp_server:latest

    - name: Build cmake project
      uses: addnab/docker-run-action@v3
      with:
        image: cpp_server:latest
        run: |
          mkdir build
          cd build
          cmake ..
          make -j $(nproc)